/**
 * Created by Indersein on 20/03/20.
 */
module.exports = {
  AdminUserController: require("./admin/AdminUserController"),
  AdminRestaurantController: require("./admin/AdminRestaurantController"),
  AdminBannerController: require("./admin/AdminBannerController"),
  AdminDriverController: require("./admin/AdminDriverController"),
  AdminFaqController: require("./admin/AdminFaqController"),
  AdminSubController: require("./admin/AdminSubController"),
  AdminPolygonController: require("./admin/AdminPolygonController"),
  AdminMenuController: require("./admin/AdminMenuController"),
  AdminOrderController: require("./admin/AdminOrderController"),
  AdminCuisineController: require("./admin/AdminCuisineController"),
  AdminPromoCodeController: require("./admin/AdminPromoCodeController"),
  AdminCustomerController: require("./admin/AdminCustomerController"),
  AdminBankController: require("./admin/AdminBankController"),
  AdminNotificationController: require("./admin/AdminNotificationController"),
  AdminPaymentGetewayController: require("./admin/AdminPaymentGetewayController"),
  AdminSettingController: require("./admin/AdminSettingController"),
  AdminFrontEndSettingController: require("./admin/AdminFrontEndSettingController"),
  AdminWalletController: require("./admin/AdminWalletController"),
  //AdminController             :   require('./AdminController'),

  ChatController: require("./ChatController"),
  CommonController: require("./CommonController"),
  CronController: require("./CronController"),
  CustomerController: require("./CustomerController"),
  DriverController: require("./DriverController"),
  RestaurantController: require("./RestaurantController"),
  RestaurantMenuController: require("./RestaurantMenuController"),
  OrderController: require("./OrderController"),
  RazorpayPaymentsController: require("./RazorpayPaymentsController"),
  RazorpayXPaymentsController: require("./RazorpayXPaymentsController"),
};
