/**
 * Created by Indersein on 15/01/21.
 */
module.exports = {
  DAOService: require("./DAO"),
  AdminService: require("./AdminService"),
  AdminMenuService: require("./AdminMenuService"),
  CityService: require("./CityService"),
  CategoryService: require("./CategoryService"),
  CustomerService: require("./CustomerService"),
  CustomerAddressService: require("./CustomerAddressService"),
  DriverService: require("./DriverService"),
  DriverBonusService: require("./DriverBonusService"),
  RestaurantService: require("./RestaurantService"),
  RestaurantAreaService: require("./RestaurantAreaService"),
  RestaurantWorkingTimeService: require("./RestaurantWorkingTimeService"),
  RestaurantMenuService: require("./RestaurantMenuService"),
  DishesService: require("./DishesService"),
  ToppingTitleService: require("./ToppingTitleService"),
  ToppingItemService: require("./ToppingItemService"),
  TransactionService: require("./TransactionTableService"),
  SubToppingItemService: require("./SubToppingItemService"),
  OrderService: require("./OrderService"),
  OrderDetailService: require("./OrderDetailService"),
  PromoCodeService: require("./PromoCodeService"),
  FaqService: require("./FaqService"),
  CuisineService: require("./CuisineService"),
  BannerService: require("./BannerService"),
  DriverOrderRequestService: require("./DriverOrderRequestService"),
  NotificationService: require("./NotificationService"),
  NotificationStoreService: require("./NotificationStoreService"),
  BankDetailService: require("./BankDetailService"),
  NotificationTextService: require("./NotificationTextService"),
  PaymentGetewayService: require("./PaymentGetewayService"),
  SettingsService: require("./SettingsService"),
  AuthenticationService: require("./AuthenticationService"),
  FrontEndSettingService: require("./FrontEndSettingsService"),
  LogService: require("./LogService"),
  FavouriteService: require("./FavouriteService"),
};
