module.exports = {
  Admin                 :   require('./AdminSchema'), 
  AdminMenu             :   require('./AdminMenuSchema'),
  CityTable             :   require('./CitySchema'),
  Category              :   require('./CategorySchema'), 
  Customer              :   require('./CustomerSchema'),
  CustomerAddress       :   require('./CustomerAddressSchema'),
  //CuisineItem         :   require('./CuisineItemSchema'),
  Driver                :   require('./DriverSchema'), 
  DriverBonus           :   require('./DriverBonusSchema'), 
  
  
  Restaurant             :   require('./RestaurantSchema'),
  RestaurantServiceArea  :   require('./RestaurantServiceArea'),
  RestaurantWorkingTime  :   require('./RestaurantWorkingTime'),
  RestaurantMenu         :   require('./MenuSchema'),
  Dishes                :   require('./DishesSchema'),
  ToppingTitle          :   require('./ToppingTitleSchema'),
  Toppings              :   require('./ToppingSchema'),
  SubTopping            :   require('./SubToppingSchema'),
  PromoCode             :   require('./PromoCodeSchema'),
  TransactionTable      :   require('./TransactionTableSchema'),

  OrderTable            :   require('./OrderSchema'),
  OrderDetailTable      :   require('./OrderDetailSchema'),
  FaqTable              :   require('./FaqSchema'),
  CuisineTable          :   require('./CuisineSchema'),
  BannerTable           :   require('./BannerSchema'),
  DriverOrderRequestTable : require('./DriverOrderRequestSchema'),
  NotificationTable     :   require('./NotificationSchema'),
  NotificationStoreTable     :   require('./NotificationStoreSchema'),
  BankDetailsTable      :   require('./BankDetails'),
  NotificationTextTable      :   require('./NotificationTextSchema'),
  PaymentGetewayTable      :   require('./PaymentGetewaySchema'),
  SettingsTable         :   require('./SettingsSchema'),
  AuthenticationTable   :   require('./Authentication'),
  FrontEndSettingsTable   :   require('./FrontEndSettingsSchema'),
  LogsTable               :    require('./LogSchema'),
  FavouriteTable         :   require('./FavouriteSchema'),
};